### ISSUE TITLE
Custom Logos not showing

### ISSUE THREAD

**Issue by itsnebulalol** [kckarnige/custom-server-logos#3]
Looks like custom logos dont show, not sure why (maybe check if the links actually point to the svg?).

Examples:
Arc | Minecraft Cosmetics: https://nebula.likes-throwing.rocks/4qbqVR
Powercord: https://nebula.likes-throwing.rocks/Eugjoh

Powercord plugins:
```text
bdCompat, better-connections, better-status-indicators, invite-inspector, MinecraftInfoPlugin, owoifier, PowercordPluginDownloader, PowercordThemeDownloader, Quick-Bot-Invite, show-all-message-buttons, silent-typing, smart-typers, text-file-viewer, theme-toggler, userid-info, voice-chat-utilities;
```

BD plugins:
```text
BDFDB, ZeresPluginLibrary, XenoLib, AutoStartRichPresence, GoogleTranslateOption, MessageLoggerV2, NitroPerks, RoleMembers, ShowHiddenChannels
```

Experiments:
```text
2020-11_poker_night, 2021-05_custom_profiles_premium, 2021-05_per_guild_avatars
```

**Comment by kckarnige** [comment]
It should only be doing that on the Powercord server, which I'm current working on fixing
Does it happen with any other servers?

**Comment by kckarnige** [comment]
Problem solved: Logo was improper size, and was fixed :3

**Comment by itsnebulalol** [comment]
Still doesn't show for Powercord or Arc | Minecraft Cosmetics. 

My themes are:
```text
Amazing Activity Cards, Custom Server Logos, Discolored, USRBG
```

**Comment by itsnebulalol** [comment]
https://real.bonix.us/51b044c.png

**Comment by itsnebulalol** [comment]
Just redownloaded and it works now

**Comment by kckarnige** [comment]
Powercord will be fixed in a later update, the logo was thrown off due to the new subscription button near the logo
